/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cct.experimental;

import cct.dialogs.JamberooFrame;
import cct.interfaces.AtomInterface;
import cct.interfaces.MoleculeInterface;
import cct.j3d.Java3dUniverse;
import cct.modelling.Molecule;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JMenuItem;
import javax.swing.JTable;

/**
 *
 * @author Vlad
 */
public class AtomListFrame extends javax.swing.JFrame {

  /**
   * Creates new form AtomListFrame
   */
  public AtomListFrame() {
    initComponents();
  }

  public void setAtomList(MoleculeInterface mol) {
    try {
      AtomList zMatrix = new AtomList();
      zMatrix.setMolecule(mol);
      zMatrix.buildAtomList();
      AtomListTableModel atomListTableModel = new AtomListTableModel(zMatrix);
      JTable jTable = new JTable(atomListTableModel);
      jScrollPane3.remove(jTable2);
      jScrollPane3.setViewportView(jTable);
      this.validate();
      this.pack();
    } catch (Exception ex) {
      ex.printStackTrace();
    }
  }

  public void setAtomList(Java3dUniverse j3d) {
    setAtomList(j3d.getMoleculeInterface());
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
   * method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel3 = new javax.swing.JPanel();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jScrollPane3 = new javax.swing.JScrollPane();
    jTable2 = new JTable();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jButton1.setText("jButton1");
    jPanel3.add(jButton1);

    jButton2.setText("jButton2");
    jPanel3.add(jButton2);

    getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

    jTable2.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    jScrollPane3.setViewportView(jTable2);

    getContentPane().add(jScrollPane3, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(AtomListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(AtomListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(AtomListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(AtomListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {

        MoleculeInterface mol = new Molecule();
        AtomInterface atom = mol.getNewAtomInstance();
        atom.setAtomicNumber(1);
        atom.setXYZ(1.07f, 0f, 0f);
        mol.addAtom(atom);

        atom = atom.getNewAtomInstance();
        atom.setAtomicNumber(6);
        atom.setXYZ(0f, 0f, 0f);
        mol.addAtom(atom);

        atom = atom.getNewAtomInstance();
        atom.setAtomicNumber(1);
        atom.setXYZ(-0.357f, -0.504f, 0.874f);
        mol.addAtom(atom);

        atom = atom.getNewAtomInstance();
        atom.setAtomicNumber(1);
        atom.setXYZ(-0.357f, -0.504f, -0.874f);
        mol.addAtom(atom);

        atom = atom.getNewAtomInstance();
        atom.setAtomicNumber(1);
        atom.setXYZ(-0.357f, 1.009f, 0.0f);
        mol.addAtom(atom);

        AtomListFrame frame = new AtomListFrame();
        frame.setAtomList(mol);
        frame.pack();
        frame.setSize(800, 400);
        frame.setVisible(true);

        if (1 < 0) {
          String[] args = new String[0];
          final JamberooFrame editor = new JamberooFrame("Jamberoo - ZMatrix Test Window", args);
          JMenuItem item = new JMenuItem("Edit Coordinates");

          editor.addMenuItem("Edit", item);

          item.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
              if (editor.getJ3DUniverse().getMoleculeInterface() == null) {
                return;
              }
              AtomListFrame frame = new AtomListFrame();
              frame.setAtomList(editor.getJ3DUniverse());
              frame.setVisible(true);
            }
          });

          editor.setSize(new Dimension(800, 600));

          editor.addWindowListener(new WindowAdapter() {

            public void windowClosing(WindowEvent we) {
              System.exit(0);
            }
          });

          editor.setVisible(true);

        }
      }
    });

  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jScrollPane3;
  private JTable jTable2;
  // End of variables declaration//GEN-END:variables
}
