/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cct.chart;

import cct.modelling.StructureManager;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author vvv900
 */
public class DataRangePanel extends javax.swing.JPanel {

  private Set<Integer> startFrameValues = new HashSet<Integer>();
  private StructureManager structureManager;

  /**
   * Creates new form DataRangePanel
   */
  public DataRangePanel() {
    initComponents();
    for (int i = 0; i < startFrameComboBox.getItemCount(); i++) {
      startFrameValues.add((Integer) startFrameComboBox.getItemAt(i));
    }
    if (startFrameComboBox.getItemCount() > 0) {
      startFrameComboBox.setSelectedIndex(0);
    }
  }

  public static void main(String[] args) {
    JDialog dialog = new JDialog();
    dialog.add(new DataRangePanel());
    dialog.validate();
    dialog.setSize(640, 480);
    dialog.setModal(true);
    dialog.setVisible(true);
    System.exit(0);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
   * content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jLabel1 = new javax.swing.JLabel();
    startFrameComboBox = new javax.swing.JComboBox();
    jLabel2 = new javax.swing.JLabel();
    jComboBox2 = new javax.swing.JComboBox();
    jLabel3 = new javax.swing.JLabel();
    jComboBox3 = new javax.swing.JComboBox();

    setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Range", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
    setLayout(new java.awt.GridBagLayout());

    jLabel1.setText("Frame to begin reading at:");
    jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.weightx = 1.0;
    add(jLabel1, gridBagConstraints);

    startFrameComboBox.setEditable(true);
    startFrameComboBox.setModel(new javax.swing.DefaultComboBoxModel(new Integer[] { 1}));
    startFrameComboBox.setToolTipText("Select Item or Enter a New One and Press Enter");
    startFrameComboBox.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        startFrameComboBoxActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    add(startFrameComboBox, gridBagConstraints);

    jLabel2.setText("Frame to stop reading at:");
    jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    add(jLabel2, gridBagConstraints);

    jComboBox2.setEditable(true);
    jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Last" }));
    jComboBox2.setToolTipText("Select Item or Enter a New One and Press Enter");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    add(jComboBox2, gridBagConstraints);

    jLabel3.setText("Data read step:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    add(jLabel3, gridBagConstraints);

    jComboBox3.setEditable(true);
    jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new Integer[] { 1, 5, 10, 15, 20, 25, 30, 35, 40, 50, 100 }));
    jComboBox3.setToolTipText("Select Item or Enter a New One and Press Enter");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    add(jComboBox3, gridBagConstraints);
    jComboBox3.getAccessibleContext().setAccessibleName("");
  }// </editor-fold>//GEN-END:initComponents

  public void setStructureManager(StructureManager structureManager) {
    this.structureManager = structureManager;
  }

  private void startFrameComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startFrameComboBoxActionPerformed
    Object obj = startFrameComboBox.getSelectedItem();
    if (obj instanceof Integer) {
      if (startFrameValues.contains( obj )) {
        return;
      }
    }
    try {
      Integer value = Integer.parseInt(obj.toString().trim());
      if (value < 0) {
        value = 0;
      }
      if (structureManager != null) {
        if (value > structureManager.getSnapshotsCount()) {
          value = structureManager.getSnapshotsCount();
        }
      }
      startFrameValues.add(value);
      startFrameComboBox.addItem(value);
      startFrameComboBox.setSelectedItem(value);
    } catch (Exception ex) {
      JOptionPane.showMessageDialog(this, obj.toString() + " is not a valid integer value!", "Error", JOptionPane.ERROR_MESSAGE);
      return;
    }

    System.out.println("Selected: " + obj.toString());
  }//GEN-LAST:event_startFrameComboBoxActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JComboBox jComboBox2;
  private javax.swing.JComboBox jComboBox3;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JComboBox startFrameComboBox;
  // End of variables declaration//GEN-END:variables
}
