/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cct.tools.ui;

import javax.swing.JOptionPane;

/**
 *
 * @author vvv900
 */
public class TruhlarExtrapolationFrame extends javax.swing.JFrame {

  /**
   * Creates new form TruhlarExtrapolationFrame
   */
  public TruhlarExtrapolationFrame() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
   * content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    Ehf2_TextField = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    Ehf3_TextField = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    alphaTextField = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    betaMP2TextField = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    betaCCSDTextField = new javax.swing.JTextField();
    jPanel2 = new javax.swing.JPanel();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setLayout(new java.awt.GridLayout(5, 2));

    jLabel1.setText("E(hf)2:");
    jPanel1.add(jLabel1);

    Ehf2_TextField.setText("0.0");
    jPanel1.add(Ehf2_TextField);

    jLabel2.setText("E(hf)3:");
    jPanel1.add(jLabel2);

    Ehf3_TextField.setText("0.0");
    Ehf3_TextField.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Ehf3_TextFieldActionPerformed(evt);
      }
    });
    jPanel1.add(Ehf3_TextField);

    jLabel3.setText("alpha:");
    jPanel1.add(jLabel3);

    alphaTextField.setText("3.4");
    jPanel1.add(alphaTextField);

    jLabel4.setText("beta(MP2):");
    jPanel1.add(jLabel4);

    betaMP2TextField.setText("2.2");
    jPanel1.add(betaMP2TextField);

    jLabel5.setText("beta(CCSD(T)):");
    jPanel1.add(jLabel5);

    betaCCSDTextField.setText("2.4");
    jPanel1.add(betaCCSDTextField);

    getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

    jButton1.setText("Calculate");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });
    jPanel2.add(jButton1);

    jButton2.setText("Cancel");
    jPanel2.add(jButton2);

    getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void Ehf3_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ehf3_TextFieldActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_Ehf3_TextFieldActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:
    double e2 = 0.0, e3 = 0, alpha, betaMP2, betaCCSD;
    try {
      e2 = Double.parseDouble(Ehf2_TextField.getText());
    } catch (Exception ex) {
      JOptionPane.showMessageDialog(this, "Wrong number for E(HF2): " + Ehf2_TextField.getText(), "Wrong number",
          JOptionPane.ERROR_MESSAGE);
      return;
    }
    try {
      e3 = Double.parseDouble(Ehf3_TextField.getText());
    } catch (Exception ex) {
      JOptionPane.showMessageDialog(this, "Wrong number for E(HF3): " + Ehf3_TextField.getText(), "Wrong number",
          JOptionPane.ERROR_MESSAGE);
      return;
    }
    try {
      alpha = Double.parseDouble(alphaTextField.getText());
    } catch (Exception ex) {
      JOptionPane.showMessageDialog(this, "Wrong number for alpha: " + alphaTextField.getText(), "Wrong number",
          JOptionPane.ERROR_MESSAGE);
      return;
    }
    try {
      betaMP2 = Double.parseDouble(betaMP2TextField.getText());
    } catch (Exception ex) {
      JOptionPane.showMessageDialog(this, "Wrong number for beta(MP2): " + betaMP2TextField.getText(), "Wrong number",
          JOptionPane.ERROR_MESSAGE);
      return;
    }
    try {
      betaCCSD = Double.parseDouble(betaCCSDTextField.getText());
    } catch (Exception ex) {
      JOptionPane.showMessageDialog(this, "Wrong number for beta(CCSD): " + betaCCSDTextField.getText(), "Wrong number",
          JOptionPane.ERROR_MESSAGE);
      return;
    }
  }//GEN-LAST:event_jButton1ActionPerformed

  
  //public double calculateTruhlarExtrapolation(double Ehf2, double Ehf3, double alpha, double beta) {
    //return Math.pow(3.0, alpha)/(Math.pow(3.0, alpha)-Math.pow(2.0, alpha)) * Ehf3 -
    //    Math.pow(2.0, alpha)/(Math.pow(3.0, alpha) - Math.pow(2.0, alpha)) * Ehf2 +
    //    Math.pow(3.0, beta)/(Math.pow(3.0, beta) - Math.pow(2.0, beta)) 
  //}
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(TruhlarExtrapolationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(TruhlarExtrapolationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(TruhlarExtrapolationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(TruhlarExtrapolationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new TruhlarExtrapolationFrame().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField Ehf2_TextField;
  private javax.swing.JTextField Ehf3_TextField;
  private javax.swing.JTextField alphaTextField;
  private javax.swing.JTextField betaCCSDTextField;
  private javax.swing.JTextField betaMP2TextField;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  // End of variables declaration//GEN-END:variables
}
