/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cct.beanshell;

import bsh.Interpreter;
import bsh.util.JConsole;
import javax.swing.JMenuItem;

/**
 *
 * @author vvv900
 */
public class BeanShellFrameTest extends javax.swing.JFrame {

  /**
   * Creates new form BeanShellFrameTest
   */
  public BeanShellFrameTest() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
   * content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu1 = new javax.swing.JMenu();
    beanShellMenuItem = new JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jMenu1.setText("File");

    beanShellMenuItem.setText("BeanShell");
    beanShellMenuItem.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        beanShellMenuItemActionPerformed(evt);
      }
    });
    jMenu1.add(beanShellMenuItem);

    jMenuBar1.add(jMenu1);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 400, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 279, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void beanShellMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beanShellMenuItemActionPerformed
    // TODO add your handling code here:
    System.out.println("MenuItem selected");
  }//GEN-LAST:event_beanShellMenuItemActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(BeanShellFrameTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(BeanShellFrameTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(BeanShellFrameTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(BeanShellFrameTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    String comm = "";
    try {
      //JConsole console = new JConsole();
      //System.setIn(console.getInputStream());
      //System.setOut(console.getOut());
      //System.setErr(console.getErr());
      //Interpreter i = new Interpreter(console);
      Interpreter i = new Interpreter();
      i.eval("importCommands(\"cct.beanshell.commands\")");
      i.eval("import java.awt.event.*");
      //i.eval("bsh.util.JConsole con = new bsh.util.JConsole()");
      i.eval("frame = new cct.beanshell.BeanShellFrameTest();");
      i.eval("frame.setVisible(true);");
      //i.eval("public void actionPerformed( java.awt.event.ActionEvent event ) { println( event ); frame.getContentPane().add(this); frame.pack(); frame.setSize(800, 600);}");
      //i.eval("frame.getBeanShellMenuItem().addActionListener( this );");
      comm = "menuItemHandler = new java.awt.event.ActionListener() { public void actionPerformed( java.awt.event.ActionEvent event ) { System.out.println(event); } };";
      i.eval(comm);
      i.eval("frame.getBeanShellMenuItem().addActionListener( menuItemHandler );");
    } catch (Exception ex) {
      ex.printStackTrace();
      System.exit(1);
    }

    /* Create and display the form 
     java.awt.EventQueue.invokeLater(new Runnable() {
     public void run() {
     new BeanShellFrameTest().setVisible(true);
     }
     });
     */
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private JMenuItem beanShellMenuItem;
  private javax.swing.JMenu jMenu1;
  private javax.swing.JMenuBar jMenuBar1;
  // End of variables declaration//GEN-END:variables

  public JMenuItem getBeanShellMenuItem() {
    return beanShellMenuItem;
  }
}
