package nanocad.util;

import java.awt.*;
public class paramDialog extends Dialog
{
	// Used for addNotify check.
	boolean fComponentsAdjusted = false;

	//{{DECLARE_CONTROLS
	TextField textField1;
	Label label1;
	Button button1;
	//}}

	class SymWindow extends java.awt.event.WindowAdapter
	{
		public void windowClosing(java.awt.event.WindowEvent event)
		{
			Object object = event.getSource();
			if (object == paramDialog.this)
				QuitDialog_WindowClosing(event);
		}
	}

	class SymAction implements java.awt.event.ActionListener
	{
		public void actionPerformed(java.awt.event.ActionEvent event)
		{
			Object object = event.getSource();
			if (object == button1)
				button1_Action(event);
			else if (object == textField1)
				textField1_EnterHit(event);

		}
	}




	public paramDialog(Frame parent, String title, boolean modal)
	{
		this(parent, modal);
		setTitle(title);
	}
	public paramDialog(Frame parent, boolean modal)
	{
		super(parent, modal);

		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		//{{INIT_CONTROLS
		setLayout(null);
		setSize(insets().left + insets().right + 323,insets().top + insets().bottom + 168);
		textField1 = new TextField();
		textField1.setBounds(insets().left + 24,insets().top + 72,276,31);
		add(textField1);
		label1 = new Label("Please enter the value to pass to this property.");
		label1.setBounds(insets().left + 24,insets().top + 24,279,28);
		add(label1);
		button1 = new Button();
		button1.setLabel("OK");
		button1.setBounds(insets().left + 228,insets().top + 120,70,26);
		button1.setBackground(new Color(12632256));
		add(button1);
		setTitle("Enter Parameter");
		setResizable(true);
		//}}

		//{{REGISTER_LISTENERS
		SymWindow aSymWindow = new SymWindow();
		this.addWindowListener(aSymWindow);
		SymAction lSymAction = new SymAction();

		button1.addActionListener(lSymAction);
		textField1.addActionListener(lSymAction);
		//}}
	}
	public void addNotify()
	{
	    // Record the size of the window prior to calling parents addNotify.
	    Dimension d = getSize();
	    
		super.addNotify();

		if (fComponentsAdjusted)
			return;

		// Adjust components according to the insets
		setSize(insets().left + insets().right + d.width, insets().top + insets().bottom + d.height);
		Component components[] = getComponents();
		for (int i = 0; i < components.length; i++)
		{
			Point p = components[i].getLocation();
			p.translate(insets().left, insets().top);
			components[i].setLocation(p);
		}
		fComponentsAdjusted = true;
	}
	void button1_Action(java.awt.event.ActionEvent event)
	{
		// to do: code goes here.
			 
		//{{CONNECTION
		// Hide the Dialog
		setVisible(false);
		//}}
			 
		//{{CONNECTION
		// Hide the Dialog
		setVisible(false);
		//}}
	}
	void QuitDialog_WindowClosing(java.awt.event.WindowEvent event)
	{
		   dispose();
	}
	public synchronized void show()
	{
		Rectangle bounds = getParent().bounds();
		Rectangle abounds = bounds();

		move(bounds.x + (bounds.width - abounds.width)/ 2,
			 bounds.y + (bounds.height - abounds.height)/2);

		super.show();
	}
	void textField1_EnterHit(java.awt.event.ActionEvent event)
	{
		// to do: code goes here.
			 
		//{{CONNECTION
		// Hide the Dialog
		setVisible(false);
		//}}
	}
}
