/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cct.dialogs;

import javax.swing.JCheckBox;
import javax.swing.JComboBox;

/**
 *
 * @author vvv900
 */
public class ImageSequencePanel extends javax.swing.JPanel {

  /**
   * Creates new form ImageSequencePanel
   */
  public ImageSequencePanel() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
   * content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    generateImageSeqCheckBox = new JCheckBox();
    jLabel1 = new javax.swing.JLabel();
    imageSeqFormatComboBox = new JComboBox();

    generateImageSeqCheckBox.setText("Generate Image Sequence");

    jLabel1.setText("Format:");

    imageSeqFormatComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(generateImageSeqCheckBox)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel1)
        .addGap(18, 18, 18)
        .addComponent(imageSeqFormatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(24, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(jLabel1)
            .addComponent(imageSeqFormatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(generateImageSeqCheckBox))
        .addContainerGap(256, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private JCheckBox generateImageSeqCheckBox;
  private JComboBox imageSeqFormatComboBox;
  private javax.swing.JLabel jLabel1;
  // End of variables declaration//GEN-END:variables

  public void setImageSeqFormatComboBox(Object[] formats) {
    if (formats == null) {
      System.err.println(this.getClass().getCanonicalName() + " : setImageSeqFormatComboBox : formats == null");
      return;
    }
    imageSeqFormatComboBox.removeAllItems();
    for (Object obj : formats) {
      imageSeqFormatComboBox.addItem(obj);
    }
  }

  public JCheckBox getGenerateImageSeqCheckBox() {
    return generateImageSeqCheckBox;
  }

  public JComboBox getImageSeqFormatComboBox() {
    return imageSeqFormatComboBox;
  }
}
